### PR TITLE
ATS-541 : T-Engines - release 2.1.0-RC2

### PR DESCRIPTION
**Pull request by tzclucian**

### CODE REVIEW

**Comment by montgolfiere** [comment]
Can we add PR #122 before RC2 release (if low risk / green builds) ?

**Comment by tzclucian** [comment]
> Can we add PR #122 before RC2 release (if low risk / green builds) ?

This is PR #122 😃

**Comment by montgolfiere** [comment]
Sorry, typo - PR #121 :-)

**Comment by tzclucian** [comment]
Are these changes covered by any tests?

Are we ok waiting some more for this to be verified?

**Pull request merged**
