### PR TITLE
Sync REPO-4617_missing_mimetypes with master

### PR DESCRIPTION
**Pull request by Epurashu**

### CODE REVIEW

**Comment by montgolfiere** [comment]
How does this relate to https://github.com/Alfresco/alfresco-transform-core/pull/95 ??

**Comment by Epurashu** [comment]
@montgolfiere yes, I need to sync with master because of the *TransformerIT tests classes.

**Comment by montgolfiere** [comment]
So do still need https://github.com/Alfresco/alfresco-transform-core/pull/95 or can we close that one (without merge) ?

**Comment by Epurashu** [comment]
The changes from #95 are not into master. This sync with master is to bring the integration tests classes but the tests will be part of #95

**Pull request merged**
