### PR TITLE
REPO-4331: Update target file size check

### PR DESCRIPTION
**Pull request by eknizat**
Transformers should not throw an exception when source and target files are empty

### CODE REVIEW

**Comment by montgolfiere** [comment]
@eknizat Is this issue limited to Misc T-Engine ? I wonder if we also need a more general fix (possibly a different issue) in other T-Engines &/or Enterprise T-Router (cc @CezarLeahu).

**Comment by alandavis** [comment]
if (sourceFile.length() > 0 && targetFile.length() == 0)

@montgolfiere, I'm not sure this is something you want as a general check as there could well be cases where a transforms might result in a zero length file. However in this case we needed to allow zero length source (Strings) to result in a zero length target. The problem was that the zero length result was seen as an error.

**Comment by eknizat** [comment]
@montgolfiere This issue is limited to the Misc T-Engine from what I have seen so far. As Alan mentioned, it is caused by zero length source (Strings) transformations which get requested by solr as ACS starts up. I have not seen transformations like that for other T-Engines.

**Comment by montgolfiere** [comment]
Great, thanks

**Comment by eknizat** [comment]
Test Added.

**Pull request merged**
