### PR TITLE
Add Alfresco Releases Nexus Repository

### PR DESCRIPTION
**Pull request by skopf**
I was trying to build:

https://github.com/Alfresco/alfresco-transform-core

locally, but failed with this error:

The POM for org.alfresco:alfresco-transform-model:jar:1.0.2.11 is missing, no dependency information available

### CODE REVIEW

**Review by montgolfiere — APPROVED** [review]
LGTM

**Review by eknizat — APPROVED** [review]

**Comment by PunchedChimera** [comment]
Is access to https://artifacts.alfresco.com/nexus/content/repositories/releases not sufficient?

**Comment by montgolfiere** [comment]
@PunchedChimera Are you referring to https://github.com/Alfresco/alfresco-transform-core/blob/master/pom.xml#L250-L253 ?

@skopf Please see above - maybe this PR is not needed (&/or additional info added to README to setup a community dev env) ?

**Comment by montgolfiere** [comment]
What's difference between "repositories" and "distributionManagement" ? May need to dig out a Maven docs link ;-)

Does latter need extra edit to "settings.xml" or ...

**Review by montgolfiere — COMMENTED** [review]
Further comments added.

**Review by montgolfiere — COMMENTED** [review]
See above comments.

**Review by montgolfiere — COMMENTED** [review]
...

**Review by TheOutsSeeker — COMMENTED** [review]
Please add  section similar to 
<repository>
  	<name>Alfresco Maven Repository</name>
  	<id>maven.alfresco.com</id>
  	<url>http://maven.alfresco.com/nexus/content/groups/public/</url>
  </repository>

to your settings.xml instead of asking to extend project's pom.xml.

I am not in favour of this PR and therefore disapprove it.

**Comment by montgolfiere** [comment]
FYI: @TheOutsSeeker @PunchedChimera some more info from @skopf 

> repositories tells maven where to get artifacts from. By default, it only has maven central. The distribution management defines where maven publishes new artifacts to.
> 
> See
> https://maven.apache.org/pom.html#repositories
> vs
> https://maven.apache.org/pom.html#Distribution_Management
> and also
> https://maven.apache.org/guides/mini/guide-multiple-repositories.html

If the PR is benign, any reason not to accept (rather than an explicit README update) ?

**Review by PunchedChimera — APPROVED** [review]

**Comment by montgolfiere** [comment]
Since no further comments or issues raised, I'll close this PR as a stale. We can re-open and revisit in future, if needed.

**Pull request closed without merging**
