### PR TITLE
MNT-21869 libreoffice timeout set too high

### PR DESCRIPTION
**Pull request by Epurashu**
Reduce default value of timeout for libreoffice from 2000min to 20min
   Add option to configure libreoffice timeout externally.

### CODE REVIEW

**Comment by Epurashu** [comment]
Created this PR to decide if the approach is correct.
Marked it as WIP as extra testing is required to decide the proper value of timeout. Also this property needs to be documented.

**Comment by montgolfiere** [comment]
As discussed, should we not externalise all hard-coded JodConverter properties (with existing defaults) to give advanced deployers more options ? See also related MNT-xxxxx for support request to externalise the port string.

**Review by montgolfiere — COMMENTED** [review]
See comment above.

**Review by TheOutsSeeker — APPROVED** [review]
I am okay with 20 mins as default and the way the property is externalised.

**Review by KikoUK — APPROVED** [review]
LGTM

**Comment by TheOutsSeeker** [comment]
Fixed the WS scan task which failed due to company policy violation by ignoring to libs - spring-web-5.2.7 and tomcat-emved-core-9.0.36. Build is green now.

**Comment by Epurashu** [comment]
Thank you @TheOutsSeeker for helping with the WS fail.

I think at this point I`m done with adding changes, I`ve re-requested reviews :)

**Review by TheOutsSeeker — APPROVED** [review]

**Pull request merged**
